rm -Rf "/home/$USER/.config/nvim"
rm -Rf "/home/$USER/.config/kitty"
rm -Rf "/home/$USER/.config/alacritty"
rm -Rf "/home/$USER/.zshrc"
rm -Rf "/home/$USER/.config/starship.toml"

ln -s "$PWD/nvim" "/home/$USER/.config/nvim"
ln -s "$PWD/kitty" "/home/$USER/.config/kitty"
ln -s "$PWD/alacritty" "/home/$USER/.config/alacritty"
ln -s "$PWD/.zshrc" "/home/$USER/.zshrc"
ln -s "$PWD/starship.toml" "/home/$USER/.config/starship.toml"
